"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { searchBusinesses, type Business } from "@/lib/businesses";
import { extractApiError } from "@/lib/api";
import AppTaskbar from "@/components/layout/AppTaskbar";
import MapViewLazy, { type MapMarker } from "@/components/map/MapViewLazy";
type RunSearch=(params:{q?:string;city?:string})=>Promise<void>
export default function SearchPage(){const [q,setQ]=useState("");const [city,setCity]=useState("");const [items,setItems]=useState<Business[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const runSearch:RunSearch=async(params)=>{setLoading(true);setError(null);try{const result=await searchBusinesses({...params,limit:20});setItems(result.data??result as unknown as Business[])}catch(err){setError(extractApiError(err));setItems([])}finally{setLoading(false)}};useEffect(()=>{let active=true;searchBusinesses({limit:20}).then(r=>{if(active)setItems(r.data??r as unknown as Business[])}).catch(err=>{if(active){setError(extractApiError(err));setItems([])}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);async function submit(e:React.FormEvent){e.preventDefault();await runSearch({q:q||undefined,city:city||undefined})}return <main dir="rtl" className="min-h-screen bg-night px-4 pb-10 pt-36 text-white">
  <AppTaskbar /><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-black">جست‌وجوی کسب‌وکار</h1><form onSubmit={submit} className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 md:grid-cols-[1fr_220px_auto]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="نام، خدمت یا دسته‌بندی" className="rounded-xl bg-white/10 p-4 outline-none"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="شهر" className="rounded-xl bg-white/10 p-4 outline-none"/><button className="btn btn-primary px-6 font-bold">{loading?"در حال جست‌وجو…":"جست‌وجو"}</button></form><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="grid gap-4">{error&&<p className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</p>}{!loading&&!error&&items.length===0&&<p className="rounded-2xl border border-white/10 bg-white/5 p-6 text-center text-sm text-surface-variant">کسب‌وکاری یافت نشد. فیلترها را تغییر دهید یا شهر دیگری را جست‌وجو کنید.</p>}{items.map(b=><article key={b.id} className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex justify-between gap-4"><div><p className="text-sm text-secondary">{b.category??"کسب‌وکار محلی"}</p><h2 className="mt-2 text-xl font-bold">{b.name}</h2><p className="mt-2 text-sm text-surface-variant">{[b.city,b.neighborhood,b.address].filter(Boolean).join("، ")}</p></div>{b.distance&&<span className="text-sm text-surface-variant">{Math.round(b.distance)} متر</span>}</div><div className="mt-4 flex gap-3"><Link href={`/b/${b.slug}`} className="btn btn-primary btn-sm">مشاهده</Link>{b.phone&&<a href={`tel:${b.phone}`} className="btn btn-secondary btn-sm">تماس</a>}</div></article>)}</section><MapViewLazy className="h-[560px] w-full" markers={items.filter(b=>b.latitude!=null&&b.longitude!=null).map((b): MapMarker => ({id: b.id, latitude: b.latitude as number, longitude: b.longitude as number, title: b.name, subtitle: [b.category, b.distance?`${Math.round(b.distance)} متر`:null].filter(Boolean).join(" — "), href: `/b/${b.slug}`}))} /></div></div></main>}
